name: Perft
run-name: Run perft test
on: [push]
jobs:
  Run-Perft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure project
        run: cmake -S . -B build

      - name: Build perft target
        run: cmake --build build --target Perft

      - name: Run perft test
        run: ./build/Perft
